const PIN_KEY="milar_os_pin";const sb=supabase.createClient(window.MILAR_SUPABASE_URL,window.MILAR_SUPABASE_KEY);let people=[],operations=[],meetings=[],radar=[],recognition=null;setInterval(()=>{if(document.getElementById("ambientTime"))ambientTime.textContent=new Date().toLocaleTimeString("es-ES",{hour:"2-digit",minute:"2-digit"})},1000);
function unlock(){const pin=localStorage.getItem(PIN_KEY)||"1209";if(pinInput.value===pin){lockScreen.classList.add("hidden");mainApp.classList.remove("hidden");loadAll()}else alert("Código incorrecto")}function lock(){mainApp.classList.add("hidden");lockScreen.classList.remove("hidden");pinInput.value=""}
function showAmbient(){dashboard.classList.add("hidden");ambientScreen.classList.remove("hidden");updateAmbient()}function showDashboard(){ambientScreen.classList.add("hidden");dashboard.classList.remove("hidden")}function updateAmbient(){let active=operations.filter(x=>x.status!=="cerrado"),high=active.filter(x=>x.priority==="Alta");ambientOps.textContent=active.length+" operaciones";ambientHigh.textContent=high.length+" alta prioridad";ambientMeet.textContent=meetings.length+" reuniones"}
async function loadAll(){cloudStatus.textContent="Sincronizando";const[p,o,m,r]=await Promise.all([sb.from("people").select("*").order("created_at",{ascending:false}),sb.from("operations").select("*, people(name)").order("created_at",{ascending:false}),sb.from("meetings").select("*, people(name)").order("created_at",{ascending:false}),sb.from("radar_items").select("*").order("created_at",{ascending:false})]);if(p.error||o.error||m.error||r.error){cloudStatus.textContent="Error Cloud";return}people=p.data||[];operations=o.data||[];meetings=m.data||[];radar=r.data||[];render();cloudStatus.textContent="Cloud conectado"}
function render(){const active=operations.filter(x=>x.status!=="cerrado"),high=active.filter(x=>x.priority==="Alta"),priority=active.slice().sort((a,b)=>score(b)-score(a)).slice(0,6);kpiOps.textContent=active.length;kpiHigh.textContent=high.length;kpiMeet.textContent=meetings.length;kpiPeople.textContent=people.length;priorityCount.textContent=priority.length+" activos";activeCount.textContent=active.length+" abiertos";dailySummary.textContent=`${active.length} operaciones activas · ${high.length} alta prioridad · ${meetings.length} reuniones · ${people.length} personas`;priorityList.innerHTML=priority.map(priorityHTML).join("")||"<p class='muted'>Sin prioridades.</p>";operationsList.innerHTML=active.map(operationHTML).join("")||"<p class='muted'>Sin operaciones activas.</p>";directionList.innerHTML=directionItems().map(x=>`<div class="item"><strong>${x.title}</strong><small>${x.text}</small><br><span class="tag ${x.cls}">${x.tag}</span></div>`).join("");radarAuto.innerHTML=autoRadar().map(x=>`<div class="item"><strong>${x.title}</strong><small>${x.text}</small><br><span class="tag ${x.cls}">${x.tag}</span></div>`).join("");updateAmbient()}
function score(x){let s=50;if(x.priority==="Alta")s+=35;if(/web/i.test(x.title+" "+(x.area||"")))s+=25;if(/fran|dirección|reunión/i.test(x.title+" "+(x.area||"")))s+=15;return s}
function priorityHTML(x){return `<div class="item"><strong>${esc(x.title)}</strong><small>${esc(x.area||"")}</small><br><span class="tag high">Prioridad ${score(x)}</span><div class="item-actions"><button onclick="closeOperation('${x.id}')">Cerrar</button><button onclick="prepareMeeting()">Ver para Fran</button></div></div>`}
function operationHTML(x){return`<div class="item"><strong>${esc(x.title)}</strong><small>${esc(x.area||"")}</small><br><span class="tag ${x.priority==="Alta"?"high":"medium"}">${esc(x.priority||"Media")}</span><div class="item-actions"><button onclick="closeOperation('${x.id}')">Cerrar</button></div></div>`}
function directionItems(){let active=operations.filter(x=>x.status!=="cerrado"),web=active.filter(x=>/web|dobuss/i.test(x.title+" "+(x.area||""))),auth=active.filter(x=>/autoriza|aprobar|fran|gerente/i.test(x.title+" "+(x.area||"")));return[{title:"Web",text:web.length?`${web.length} tema(s) para revisar con Fran`:"Prioridad activa: preparar puntos web",tag:"PRIORIDAD",cls:"high"},{title:"Autorizaciones",text:auth.length?`${auth.length} autorización(es) pendiente(s)`:"Sin autorizaciones detectadas",tag:"FRAN",cls:"medium"},{title:"Última reunión",text:meetings[0]?.title||"Sin reunión guardada",tag:"HISTÓRICO",cls:"blue"}]}
function autoRadar(){let active=operations.filter(x=>x.status!=="cerrado"),high=active.filter(x=>x.priority==="Alta");return[{title:"Sistema operativo",text:`${active.length} operaciones abiertas. ${high.length} de alta prioridad.`,tag:"JARVIS",cls:high.length?"high":"blue"},{title:"Pedro Ortiz 2025",text:"Punto 1,79, dto 6%+2%, IVA y margen 56%.",tag:"TARIFA",cls:"blue"},{title:"Modo TV 55”",text:"Panel ambiente activo para pantalla extendida.",tag:"VISUAL",cls:"medium"}]}
async function closeOperation(id){await sb.from("operations").update({status:"cerrado",closed_at:new Date().toISOString()}).eq("id",id);loadAll()}
function openJarvisVoice(){modalTitle.textContent="Hablar con JARVIS";modalText.innerHTML=`<div class="meeting-box"><b>Modo voz de prueba</b><p>Di una orden. Por ahora crea capturas y pruebas de dictado. Con micrófono USB al PC funcionará mejor.</p></div><textarea id="quickText" placeholder="Ej: Jarvis, apunta que tengo que revisar la web con Fran."></textarea><button class="link-btn" onclick="dictateInto('quickText')">Iniciar dictado</button>`;modalActions.innerHTML=`<button class="primary" onclick="saveQuickCapture()">Guardar orden</button><button class="link-btn" onclick="speakJarvis()">Probar voz de Jarvis</button>`;modal.classList.remove("hidden")}
function speakJarvis(){speak("Sistema JARVIS operativo. Cloud conectado. Preparado para trabajar, Daniel.")}
function openQuickCapture(){modalTitle.textContent="Captura rápida";modalText.innerHTML=`<textarea id="quickText" placeholder="Ej: Cliente Manuel. Sofá gris. Llamar lunes."></textarea><button class="link-btn" onclick="dictateInto('quickText')">Dictar</button>`;modalActions.innerHTML=`<button class="primary" onclick="saveQuickCapture()">Guardar</button>`;modal.classList.remove("hidden")}
async function saveQuickCapture(){if(!quickText.value.trim())return;let text=quickText.value.trim();let priority=/urgente|fran|web|autoriza/i.test(text)?"Alta":"Media";await sb.from("operations").insert({title:text,area:"Captura rápida JARVIS",priority,status:"activo"});closeModal();loadAll();speak("Orden guardada.")}
function prepareMeeting(){const active=operations.filter(x=>x.status!=="cerrado"),web=active.filter(x=>/web|dobuss/i.test(x.title+" "+(x.area||""))),altas=active.filter(x=>x.priority==="Alta");modalTitle.textContent="Centro Dirección · Fran";modalText.innerHTML=`<div class="meeting-box"><h3>Guion de reunión</h3><p><b>Prioridad:</b> Web</p><p><b>Operaciones abiertas:</b> ${active.length}</p><p><b>Alta prioridad:</b> ${altas.length}</p></div><h4>Temas para tratar</h4>${[...web,...altas].slice(0,10).map(x=>`<div class="item"><strong>${esc(x.title)}</strong><small>${esc(x.area||"")}</small></div>`).join("")||"<p class='muted'>No hay temas críticos detectados.</p>"}<textarea id="prepNotes" placeholder="Añadir temas para que Fran autorice o decida..."></textarea>`;modalActions.innerHTML=`<button class="primary" onclick="savePrepFran()">Guardar preparación</button><button class="link-btn" onclick="openMeetingRecorder()">Grabar ahora</button>`;modal.classList.remove("hidden")}
async function savePrepFran(){await sb.from("meetings").insert({title:"Preparación Fran "+new Date().toLocaleDateString("es-ES"),summary:prepNotes.value||"",status:"preparada"});closeModal();loadAll()}
function openMeetingRecorder(){modalTitle.textContent="Reunión Fran";modalText.innerHTML=`<div id="recState" class="meeting-box">Listo para dictar.</div><textarea id="meetingTranscript" placeholder="Transcripción o notas..."></textarea><label>Resumen ejecutivo</label><textarea id="meetingSummary"></textarea><label>Tareas detectadas</label><textarea id="meetingTasks" placeholder="Una tarea por línea."></textarea>`;modalActions.innerHTML=`<button class="primary" onclick="startMeetingDictation()">Iniciar dictado</button><button class="link-btn" onclick="stopMeetingDictation()">Parar</button><button class="link-btn" onclick="autoSummarizeMeeting()">Resumen rápido</button><button class="primary" onclick="saveMeetingFull()">Guardar reunión</button>`;modal.classList.remove("hidden")}
function startMeetingDictation(){if(!('webkitSpeechRecognition'in window)&&!('SpeechRecognition'in window)){alert("Este navegador no permite dictado directo. Usa dictado del teclado o pega transcripción.");return}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new SR();recognition.lang="es-ES";recognition.continuous=true;recognition.interimResults=true;recState.innerHTML='<span class="recording">Grabando / dictando...</span>';recognition.onresult=e=>{let final="";for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)final+=e.results[i][0].transcript+" "}meetingTranscript.value+=final};recognition.start()}
function stopMeetingDictation(){if(recognition)recognition.stop();if(document.getElementById("recState"))recState.textContent="Dictado detenido."}
function autoSummarizeMeeting(){let t=meetingTranscript.value.trim();let lines=t.split(/[\\.\\n]/).map(x=>x.trim()).filter(Boolean);let key=lines.filter(x=>/web|dobuss|autoriza|pendiente|cliente|presupuesto|marketing|venta|armario|sof[aá]|colch[oó]n/i.test(x));meetingSummary.value=`Resumen rápido:\n${(key.length?key:lines).slice(0,8).map(x=>"• "+x).join("\n")}\n\nAutorizaciones/decisiones:\n• Revisar y confirmar.`;meetingTasks.value=(key.length?key:lines).slice(0,7).map(x=>"Revisar: "+x).join("\n")}
async function saveMeetingFull(){let title="Reunión Fran "+new Date().toLocaleDateString("es-ES");await sb.from("meetings").insert({title,summary:(meetingSummary.value||meetingTranscript.value||"").trim(),status:"cerrada"});let tasks=(meetingTasks.value||"").split("\n").map(x=>x.trim()).filter(Boolean);for(const task of tasks){await sb.from("operations").insert({title:task,area:"Reunión Fran",priority:"Alta",status:"activo"})}closeModal();loadAll();speak("Reunión guardada y tareas creadas.")}
function openTariffCalc(){modalTitle.textContent="Tarifa Pedro Ortiz";modalText.innerHTML=`<p class="muted">Punto 1,79 · dto 6% + 2% PP · margen 56% · IVA 21%.</p><input id="calcModel" placeholder="Modelo / módulo"><input id="calcPoints" type="number" step="0.01" placeholder="Puntos"><input id="calcExtras" type="number" step="0.01" value="0" placeholder="Extras"><select id="calcType"><option value="normal">Normal con descuento</option><option value="promo">Promoción / sin descuento</option></select><div id="calcOutput" class="item hidden"></div>`;modalActions.innerHTML=`<button class="primary" onclick="calculatePedroOrtiz()">Calcular PVP</button><button class="link-btn" onclick="saveTariffAsOperation()">Guardar operación</button>`;modal.classList.remove("hidden")}
function calculatePedroOrtiz(){const pts=(parseFloat(calcPoints.value)||0)+(parseFloat(calcExtras.value)||0),bruto=pts*1.79,coste=calcType.value==="promo"?bruto:bruto*0.94*0.98,pvpSinIva=coste/(1-0.56),pvpIva=pvpSinIva*1.21;calcOutput.classList.remove("hidden");calcOutput.innerHTML=`<strong>PVP recomendado: ${eur(pvpIva)}</strong><small>Coste neto: ${eur(coste)} · Beneficio sin IVA: ${eur(pvpSinIva-coste)}</small><br>Puntos: ${pts.toFixed(2)} · Bruto: ${eur(bruto)} · IVA: ${eur(pvpIva-pvpSinIva)}`}
async function saveTariffAsOperation(){calculatePedroOrtiz();await sb.from("operations").insert({title:"Presupuesto Pedro Ortiz: "+(calcModel.value||"sin modelo"),area:"Tarifa Pedro Ortiz",priority:"Media",notes:calcOutput.innerText,status:"activo"});closeModal();loadAll()}
function openNewOperation(){modalTitle.textContent="Nueva operación";modalText.innerHTML='<input id="opTitle" placeholder="Título"><input id="opArea" placeholder="Área"><select id="opPriority"><option>Alta</option><option selected>Media</option><option>Baja</option></select><textarea id="opNotes" placeholder="Notas"></textarea>';modalActions.innerHTML='<button class="primary" onclick="saveOperation()">Guardar</button>';modal.classList.remove("hidden")}
async function saveOperation(){if(!opTitle.value.trim())return;await sb.from("operations").insert({title:opTitle.value,area:opArea.value,priority:opPriority.value,notes:opNotes.value,status:"activo"});closeModal();loadAll()}
function openRadar(){showModal("Radar JARVIS",autoRadar().map(x=>`<div class="item"><strong>${x.title}</strong><small>${x.text}</small></div>`).join(""))}function openSettings(){modalTitle.textContent="Ajustes";modalText.innerHTML='<label>Cambiar código</label><input id="newPin" inputmode="numeric" type="password" maxlength="6"><p class="muted">El código nunca se muestra en la portada.</p>';modalActions.innerHTML='<button class="primary" onclick="savePin()">Guardar</button>';modal.classList.remove("hidden")}function savePin(){if(newPin.value.length<4){alert("Mínimo 4 dígitos");return}localStorage.setItem(PIN_KEY,newPin.value);closeModal()}
function searchGlobal(q){q=q.trim().toLowerCase();if(!q){searchResults.classList.add("hidden");return}const all=[...operations.map(x=>({kind:"Operación",title:x.title,sub:x.area||""})),...people.map(x=>({kind:"Persona",title:x.name,sub:x.area||""})),...meetings.map(x=>({kind:"Reunión",title:x.title,sub:x.summary||""}))].filter(x=>(x.title+" "+x.sub+" "+x.kind).toLowerCase().includes(q));searchResults.classList.remove("hidden");searchResults.innerHTML=all.slice(0,8).map(x=>`<div class="result-row"><b>${esc(x.title)}</b><br><small>${x.kind} · ${esc(x.sub)}</small></div>`).join("")||"<p>Sin resultados.</p>"}
function dictateInto(id){if(!('webkitSpeechRecognition'in window)&&!('SpeechRecognition'in window)){alert("Usa el dictado del teclado del móvil.");return}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let r=new SR();r.lang="es-ES";r.onresult=e=>document.getElementById(id).value+=e.results[0][0].transcript;r.start()}function speak(text){if(!("speechSynthesis"in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="es-ES";u.rate=.98;speechSynthesis.speak(u)}function showModal(t,html){modalTitle.textContent=t;modalText.innerHTML=html;modalActions.innerHTML="";modal.classList.remove("hidden")}function closeModal(){modal.classList.add("hidden")}function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}function eur(n){return new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"}).format(n||0)}
